// This is an autogenerated file from Firebase Genkit.
'use server';
/**
 * @fileOverview An anime recommendation AI agent.
 *
 * - animeRecommendations - A function that handles the anime recommendation process.
 * - AnimeRecommendationsInput - The input type for the animeRecommendations function.
 * - AnimeRecommendationsOutput - The return type for the animeRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnimeRecommendationsInputSchema = z.object({
  viewingHistory: z
    .array(z.string())
    .describe('A list of anime series the user has watched.'),
});
export type AnimeRecommendationsInput = z.infer<
  typeof AnimeRecommendationsInputSchema
>;

const AnimeRecommendationsOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('A list of recommended anime series for the user.'),
});
export type AnimeRecommendationsOutput = z.infer<
  typeof AnimeRecommendationsOutputSchema
>;

export async function animeRecommendations(
  input: AnimeRecommendationsInput
): Promise<AnimeRecommendationsOutput> {
  return animeRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'animeRecommendationsPrompt',
  input: {schema: AnimeRecommendationsInputSchema},
  output: {schema: AnimeRecommendationsOutputSchema},
  prompt: `You are an expert anime recommendation agent. Given a user's viewing history, you will recommend new anime series for the user to explore.

  The recommendations should be based on the user's viewing history, and should be anime series that the user is likely to enjoy.

  Here is the user's viewing history:
  {{#each viewingHistory}}
  - {{this}}
  {{/each}}
  `,
});

const animeRecommendationsFlow = ai.defineFlow(
  {
    name: 'animeRecommendationsFlow',
    inputSchema: AnimeRecommendationsInputSchema,
    outputSchema: AnimeRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
