// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides intelligent anime recommendations based on collaborative filtering.
 *
 * - intelligentAnimeRecommendations - A function that suggests new anime for a user to explore.
 * - IntelligentAnimeRecommendationsInput - The input type for the intelligentAnimeRecommendations function.
 * - IntelligentAnimeRecommendationsOutput - The return type for the intelligentAnimeRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IntelligentAnimeRecommendationsInputSchema = z.object({
  userWatchHistory: z
    .array(z.string())
    .describe('List of anime titles the user has watched.'),
  otherUsersWatchHistory: z
    .array(z.object({userId: z.string(), watchHistory: z.array(z.string())}))
    .describe(
      'An array of objects containing the userId and their corresponding anime watch history.'
    ),
  numberOfRecommendations: z
    .number()
    .default(5)
    .describe('The number of anime recommendations to return.'),
});

export type IntelligentAnimeRecommendationsInput = z.infer<
  typeof IntelligentAnimeRecommendationsInputSchema
>;

const IntelligentAnimeRecommendationsOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('A list of recommended anime titles based on collaborative filtering.'),
});

export type IntelligentAnimeRecommendationsOutput = z.infer<
  typeof IntelligentAnimeRecommendationsOutputSchema
>;

export async function intelligentAnimeRecommendations(
  input: IntelligentAnimeRecommendationsInput
): Promise<IntelligentAnimeRecommendationsOutput> {
  return intelligentAnimeRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'intelligentAnimeRecommendationsPrompt',
  input: {schema: IntelligentAnimeRecommendationsInputSchema},
  output: {schema: IntelligentAnimeRecommendationsOutputSchema},
  prompt: `You are an AI expert in recommending Anime. Based on the provided user watch history and watch history of other users, you will provide personalized anime recommendations.

User Watch History: {{{userWatchHistory}}}
Other Users Watch History: {{#each otherUsersWatchHistory}}{{{userId}}}: {{{watchHistory}}} {{/each}}
Number of Recommendations: {{{numberOfRecommendations}}}

Recommendations:`, // Removed backticks; Handlebars uses triple curly braces for variable values.
});

const intelligentAnimeRecommendationsFlow = ai.defineFlow(
  {
    name: 'intelligentAnimeRecommendationsFlow',
    inputSchema: IntelligentAnimeRecommendationsInputSchema,
    outputSchema: IntelligentAnimeRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
